opam-version: "2.0"
lib: [
  "_build/install/default/lib/integers/META"
  "_build/install/default/lib/integers/dune-package"
  "_build/install/default/lib/integers/integers.a"
  "_build/install/default/lib/integers/integers.cma"
  "_build/install/default/lib/integers/integers.cmxa"
  "_build/install/default/lib/integers/libintegers_stubs.a"
  "_build/install/default/lib/integers/ocaml_integers.h"
  "_build/install/default/lib/integers/opam"
  "_build/install/default/lib/integers/signed.cmi"
  "_build/install/default/lib/integers/signed.cmt"
  "_build/install/default/lib/integers/signed.cmti"
  "_build/install/default/lib/integers/signed.cmx"
  "_build/install/default/lib/integers/signed.ml"
  "_build/install/default/lib/integers/signed.mli"
  "_build/install/default/lib/integers/top/install_integer_printers.cmi"
    {"top/install_integer_printers.cmi"}
  "_build/install/default/lib/integers/top/install_integer_printers.cmt"
    {"top/install_integer_printers.cmt"}
  "_build/install/default/lib/integers/top/install_integer_printers.cmti"
    {"top/install_integer_printers.cmti"}
  "_build/install/default/lib/integers/top/install_integer_printers.ml"
    {"top/install_integer_printers.ml"}
  "_build/install/default/lib/integers/top/install_integer_printers.mli"
    {"top/install_integer_printers.mli"}
  "_build/install/default/lib/integers/top/integer_printers.cmi"
    {"top/integer_printers.cmi"}
  "_build/install/default/lib/integers/top/integer_printers.cmt"
    {"top/integer_printers.cmt"}
  "_build/install/default/lib/integers/top/integer_printers.cmti"
    {"top/integer_printers.cmti"}
  "_build/install/default/lib/integers/top/integer_printers.ml"
    {"top/integer_printers.ml"}
  "_build/install/default/lib/integers/top/integer_printers.mli"
    {"top/integer_printers.mli"}
  "_build/install/default/lib/integers/top/integers_top.cma"
    {"top/integers_top.cma"}
  "_build/install/default/lib/integers/unsigned.cmi"
  "_build/install/default/lib/integers/unsigned.cmt"
  "_build/install/default/lib/integers/unsigned.cmti"
  "_build/install/default/lib/integers/unsigned.cmx"
  "_build/install/default/lib/integers/unsigned.ml"
  "_build/install/default/lib/integers/unsigned.mli"
]
stublibs: "_build/install/default/lib/stublibs/dllintegers_stubs.so"
doc: [
  "_build/install/default/doc/integers/CHANGES.md"
  "_build/install/default/doc/integers/LICENSE.md"
  "_build/install/default/doc/integers/README.md"
]
libexec: "_build/install/default/lib/integers/integers.cmxs"
