(* generated by dune *)

(** @canonical Merlin_index_format.Index_cache *)
module Index_cache = Merlin_index_format__Index_cache

(** @canonical Merlin_index_format.Index_format *)
module Index_format = Merlin_index_format__Index_format
